Repository AY2122S2-CS2113-T11-2/tp, pull requests merged in 2022-04, with the labels that each got.

#44 Add SearchDoctorCommand.java, SearchPatientCommand.java, SearchAppointmentCommand.java
  data/IHospitalAppointments.txt
  data/IHospitalDoctors.txt
  data/IHospitalPatients.txt
  src/main/java/tp/AppointmentList.java
  src/main/java/tp/DoctorList.java
  src/main/java/tp/Parser.java
  src/main/java/tp/PatientList.java
  src/main/java/tp/SearchAppointmentCommand.java
  src/main/java/tp/SearchDoctorCommand.java
  src/main/java/tp/SearchPatientCommand.java
  src/main/java/tp/person/Doctor.java
  src/main/java/tp/person/Patient.java
  src/main/java/tp/person/Person.java
Labels: v2.0

#46 patient description and symptom
  docs/DeveloperGuide.md
  docs/patient.png
  docs/updatePatient.jpg
  src/main/java/tp/AddPatientCommand.java
  src/main/java/tp/AddPatientDescriptionCommand.java
  src/main/java/tp/AppointmentStorage.java
  src/main/java/tp/Parser.java
  src/main/java/tp/PatientList.java
  src/main/java/tp/PatientStorage.java
  src/main/java/tp/person/Doctor.java
  src/main/java/tp/person/Patient.java
Labels: v2.0

#48 Fix some bugs and update User Guide
  docs/UserGuide.md
  src/main/java/tp/AppointmentList.java
  src/main/java/tp/DoctorList.java
  src/main/java/tp/Parser.java
  src/main/java/tp/PatientList.java
  src/main/java/tp/Ui.java
Labels: v2.0

#91 Fixed Exception Handling issues for Delete and Search, made code improvements
  docs/UserGuide.md
  src/main/java/tp/AppointmentList.java
  src/main/java/tp/DoctorList.java
  src/main/java/tp/Parser.java
  src/main/java/tp/PatientList.java
  src/main/java/tp/command/DeleteAppointmentCommand.java
  src/main/java/tp/command/DeleteDoctorCommand.java
  src/main/java/tp/command/DeletePatientCommand.java
  src/main/java/tp/command/SearchDoctorCommand.java
  src/main/java/tp/command/SearchPatientCommand.java
Labels: v2.1

#96 Add edit appointment
  docs/UserGuide.md
  src/main/java/seedu/duke/Duke.java
  src/main/java/tp/Appointment.java
  src/main/java/tp/AppointmentList.java
  src/main/java/tp/DoctorList.java
  src/main/java/tp/Parser.java
  src/main/java/tp/Ui.java
  src/main/java/tp/command/AddAppointmentCommand.java
  src/main/java/tp/command/EditAppointmentCommand.java
  src/main/java/tp/command/SearchDoctorCommand.java
  src/main/java/tp/command/SearchPatientCommand.java
  src/main/java/tp/person/Patient.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: v2.1

#97 Add exceptions for duplicate ID
  docs/UserGuide.md
  src/main/java/tp/DoctorList.java
  src/main/java/tp/PatientList.java
  src/main/java/tp/command/EditAppointmentCommand.java
Labels: v2.1

#98 Add exceptions for deleting out-of-bound elements
  docs/UserGuide.md
  src/main/java/tp/Parser.java
  src/main/java/tp/command/DeleteAppointmentCommand.java
  src/main/java/tp/command/DeleteDoctorCommand.java
  src/main/java/tp/command/DeletePatientCommand.java
  src/main/java/tp/command/EditDoctorCommand.java
  src/main/java/tp/command/EditPatientCommand.java
Labels: v2.1

#117 Add PPP
  docs/team/ZhouQi.md
  src/main/java/tp/Ward.java
  src/main/java/tp/person/Patient.java
Labels: documentation, v2.1

#118 Fix bugs for adding ward
  docs/UserGuide.md
  docs/team/cczhouqi.md
  src/main/java/tp/Parser.java
  src/main/java/tp/Ui.java
  src/main/java/tp/command/AddWardCommand.java
  src/main/java/tp/command/DeleteDoctorCommand.java
  src/main/java/tp/command/DeleteNurseCommand.java
  src/main/java/tp/command/DeletePatientCommand.java
  src/main/java/tp/command/DeleteWardCommand.java
  src/main/java/tp/command/HelpCommand.java
Labels: v2.1

#124 edited ward classes and assigned some code authorship from nurse classes and methods to sethlxk
  src/main/java/tp/IHospital.java
  src/main/java/tp/NurseList.java
  src/main/java/tp/Parser.java
  src/main/java/tp/Ui.java
  src/main/java/tp/Ward.java
  src/main/java/tp/WardList.java
  src/main/java/tp/WardStorage.java
  src/main/java/tp/command/AddWardCommand.java
  src/main/java/tp/person/Nurse.java
Labels: v2.1

#125 Set doctor/nurse(s) default ward number
  docs/AddDoctorOutput.png
  docs/UserGuide.md
  docs/team/cczhouqi.md
  src/main/java/tp/NurseStorage.java
  src/main/java/tp/Parser.java
  src/main/java/tp/Ui.java
  src/main/java/tp/command/AddAppointmentCommand.java
  src/main/java/tp/command/AddDoctorCommand.java
  src/main/java/tp/command/AddPatientCommand.java
  src/main/java/tp/command/DeleteAppointmentCommand.java
  src/main/java/tp/command/DeleteDoctorCommand.java
  src/main/java/tp/command/DeletePatientCommand.java
  src/test/java/tp/AppointmentTest.java
  src/test/java/tp/person/DoctorTest.java
  src/test/java/tp/person/PatientTest.java
  src/test/java/tp/person/PersonTest.java
Labels: v2.1

#127 Fix minor bugs
  docs/ListDoctorOutput.png
  docs/UserGuide.md
  src/main/java/tp/DoctorStorage.java
Labels: v2.1
